### ISSUE TITLE
yle-dl: AdobeHDS.php manifest mismatch

### ISSUE THREAD

**Issue by skrinakron** [teknohog/ebuilds#3]
The yle-dl-2.10.0 ebuild fails to merge because the current AdobeHDS.php doesn't match the manifest (size 93421 instead of 93138). Would it be possible to update the manifest and/or make the ebuild(s) fetch the revision the checksums were derived from?

**Comment by teknohog** [comment]
Thanks for the notice, it should be fixed now.

The problem here is that AdobeHDS.php doesn't have any versioning, so the correct version basically depends on the source URL. Also, the package seems to work with other versions, so I don't always notice the problem.
