### ISSUE TITLE
Extra yle-dl version in manifest

### ISSUE THREAD

**Issue by skrinakron** [teknohog/ebuilds#5]
The manifest file for net-misc/yle-dl contains a line for version 2.24, for which the repo doesn't have an ebuild. Relying on this default manifest causes attempts to merge yle-dl to error out with "a file listed in the Manifest could not be found".

**Comment by teknohog** [comment]
Thanks for catching this error, I've added the missing file. I must say I haven't been updating this lately as the dependencies have gotten more complicated. I use https://github.com/juippis/jps-gentoo/tree/master/media-video/yle-dl now.
